### ISSUE TITLE
Update sandbox

### ISSUE THREAD

**Issue by marleyg** [InterWorkAlliance/visual-token-designer#3]
@djnicholson can we update the sandbox again, I forgot to rename one of the property sets.

**Comment by djnicholson** [comment]
No problem, I'll get on to this tomorrow (or worst case, over the weekend).

Do we want it published to the VS Code marketplace again once I have a new build?

**Comment by marleyg** [comment]
Publish again if you can, the name change was kinda a big deal for certain audiences.
